ALTER TABLE "api_keys"
  ADD COLUMN IF NOT EXISTS "rate_limit" INTEGER NOT NULL DEFAULT 60,
  ADD COLUMN IF NOT EXISTS "ip_whitelist" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "revoked_at" TIMESTAMP(3);
